### ISSUE TITLE
onError触发后会触发调用onAfter吗

### ISSUE THREAD

**Issue by andyxialm** [hongyangAndroid/okhttputils#305]
首先感谢红羊这么棒的开源项目，在使用中想确认一个问题。
想知道在设计上，无论请求被cancel，error或者其他情况，onAfter一定会回调吗？
或者在哪些情况下不会回调？

**Comment by systemChina** [comment]
断网，请求失败不会

**Comment by act262** [comment]
`callback!=null`情况下都会调用到你的`onAfter`的吧，看代码的调用就知道失败的情况都会执行到`sendFailResultCallback`
