### ISSUE TITLE
sendto failed: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by TracesDream** [hongyangAndroid/okhttputils#324]
上传视频文件40M  出现的问题 timout 和 sendto failed: EPIPE (Broken pipe)

**Comment by zengcanxiang** [comment]
@TracesDream 兄弟 你是解决了还是怎么，我这边上传2.3M的也报这个

**Comment by TracesDream** [comment]
@zengcanxiang 是后台的问题 后台有传输限制

**Comment by zengcanxiang** [comment]
那看来我们碰上的不是同一个问题 .....  @TracesDream  谢谢了
