### ISSUE TITLE
https 设置具体的证书 无效的问题

### ISSUE THREAD

**Issue by longtaoge** [hongyangAndroid/okhttputils#331]
/**
- Created by zhy on 15/8/25.
  */
  public class MyApplication extends Application {
  private String CER_12306 = "dddd";
  private String abc = "-----BEGIN CERTIFICATE-----\n" +
          "\" +\n" +
          "            \"MIICmjCCAgOgAwIBAgIIbyZr5/jKH6QwDQYJKoZIhvcNAQEFBQAwRzELMAkGA1UEBhMCQ04xKTAn\n\" +\n" +
          "            \"BgNVBAoTIFNpbm9yYWlsIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MQ0wCwYDVQQDEwRTUkNBMB4X\n\" +\n" +
          "            \"DTA5MDUyNTA2NTYwMFoXDTI5MDUyMDA2NTYwMFowRzELMAkGA1UEBhMCQ04xKTAnBgNVBAoTIFNp\n\" +\n" +
          "            \"bm9yYWlsIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MQ0wCwYDVQQDEwRTUkNBMIGfMA0GCSqGSIb3\n\" +\n" +
          "            \"DQEBAQUAA4GNADCBiQKBgQDMpbNeb34p0GvLkZ6t72/OOba4mX2K/eZRWFfnuk8e5jKDH+9BgCb2\n\" +\n" +
          "            \"9bSotqPqTbxXWPxIOz8EjyUO3bfR5pQ8ovNTOlks2rS5BdMhoi4sUjCKi5ELiqtyww/XgY5iFqv6\n\" +\n" +
          "            \"D4Pw9QvOUcdRVSbPWo1DwMmH75It6pk/rARIFHEjWwIDAQABo4GOMIGLMB8GA1UdIwQYMBaAFHle\n\" +\n" +
          "            \"tne34lKDQ+3HUYhMY4UsAENYMAwGA1UdEwQFMAMBAf8wLgYDVR0fBCcwJTAjoCGgH4YdaHR0cDov\n\" +\n" +
          "            \"LzE5Mi4xNjguOS4xNDkvY3JsMS5jcmwwCwYDVR0PBAQDAgH+MB0GA1UdDgQWBBR5XrZ3t+JSg0Pt\n\" +\n" +
          "            \"x1GITGOFLABDWDANBgkqhkiG9w0BAQUFAAOBgQDGrAm2U/of1LbOnG2bnnQtgcVaBXiVJF8LKPaV\n\" +\n" +
          "            \"23XQ96HU8xfgSZMJS6U00WHAI7zp0q208RSUft9wDq9ee///VOhzR6Tebg9QfyPSohkBrhXQenvQ\n\" +\n" +
          "            \"og555S+C3eJAAVeNCTeMS3N/M5hzBRJAoffn3qoYdAO1Q8bTguOi+2849A==\n\" +\"ddadddd\"+\n" +
          "            \"-----END CERTIFICATE-----";
  
  @Override
  public void onCreate() {
      super.onCreate();
  
  ```
  ClearableCookieJar cookieJar1 = new PersistentCookieJar(new SetCookieCache(), new SharedPrefsCookiePersistor(getApplicationContext()));
  ```
  
  //无论设置什么证书都能通过 是否说明本方法无效
      HttpsUtils.SSLParams sslParams = HttpsUtils.getSslSocketFactory(new InputStream[]{
              new Buffer()
                      .writeUtf8(CER_12306)
                      .inputStream()}, null, null);
  //        CookieJarImpl cookieJar1 = new CookieJarImpl(new MemoryCookieStore());
      OkHttpClient okHttpClient = new OkHttpClient.Builder()
              .connectTimeout(10000L, TimeUnit.MILLISECONDS)
              .readTimeout(10000L, TimeUnit.MILLISECONDS)
              .addInterceptor(new LoggerInterceptor("TAG"))
              .cookieJar(cookieJar1)
              .sslSocketFactory(sslParams.sSLSocketFactory,sslParams.trustManager)
              .build();
      OkHttpUtils.initClient(okHttpClient);
  
  }
  }

**Comment by thomaszheng** [comment]
你访问的如果是CA认证证书的网站，手机里面就已经有他们的证书了（信任链）。只有访问使用自己生成证书的网站时，需要其对应的证书来校验。

**Comment by longtaoge** [comment]
12306 用的自己的证书吧，好像不行

**Comment by hongyangAndroid** [comment]
可以观察控制台呀，会报一些异常~~
随便输入一个字符串，会报证书异常，被catch住了；
然后走了UnSafeTrustManager的逻辑，所以和null 的效果一致。
