### ISSUE TITLE
关于和Picasso一起用的问题

### ISSUE THREAD

**Issue by a120200793** [hongyangAndroid/okhttputils#35]
你好,准备写一个项目,想用OKHTTP,发现了您写的封装 非常棒
由于您的封装可以直接集成在项目中,不用在加入okhttp,那么picasso 这个加载图片的工具,您的封装是否直接支持,还是需要另外加入okhttp的jar包

**Comment by soyoungboy** [comment]
@a120200793 引入作者的工具类，必须引入okhttp相关的库，picasso或者Glide有和okhttp对接的jar(我只用过Glide),可以餐开picasso或者Glide的官方github地址

**Comment by a120200793** [comment]
@soyoungboy  谢谢你的回答. 我在项目中测试了一下,
compile 'com.zhy:okhttputils:1.0.2' 
compile 'com.squareup.picasso:picasso:2.5.2'
两个都加上,反正图片可以加载出来了.

**Comment by eling13** [comment]
想请问下，你用okhttp+picasso，是为何？一是用okhttp来下载url，然后用picasso根据url来下载图片吗？

**Comment by a120200793** [comment]
@eling13  有的时候 用okhttp访问接口,返回的数据包括很多头像的url,在listview的adapter中,用Picasso显示头像啊
