### ISSUE TITLE
callback中onError返回的exception是返回码，如何把错误信息也输出来？

### ISSUE THREAD

**Issue by resyin** [hongyangAndroid/okhttputils#352]
正常的返回应该是： 
-- response --
400 Bad Request
...
...
{"errorCode":"000000","errorMsg":"公民身份号码没有经过合法性校验，请检查。"}

在回调中：
@Override
public void onError(Call call, Exception e, int i) {
    Logger.d(e);
}
输出：
 java.io.IOException: request failed , reponse's code is : 400

而我想输出 {"errorCode":"000000","errorMsg":"公民身份号码没有经过合法性校验，请检查。"} 这一段该如何做？

**Comment by ForgetAll** [comment]
我觉得这是有问题的，如果你能得到那个json，code应该是200！

**Comment by resyin** [comment]
服务端不在我这维护。不过我重写了okhttputils 相关的部分，直接拿了response。

**Comment by jianxiansining** [comment]
请问如何重写okhttputils 相关的部分，直接拿response？谢谢
