### ISSUE TITLE
okhttputils设置禁止重定向后，怎么获取服务器返回来的信息

### ISSUE THREAD

**Issue by tx123456** [hongyangAndroid/okhttputils#386]
设置禁止重定向后，重哪里拿到信息呢，我原来用okhttp是在onResponse里的headers拿到的，用okhttputils 直接走了onError，然后怎么拿到服务器返回的信息

**Comment by hongyang51** [comment]
你需要重写Callback validateReponse()返回 true  parseNetworkResponse() 方法参数中进行拦截

**Comment by tx123456** [comment]
已解决，多谢大佬

**Comment by hongyang51** [comment]
@tx123456 我菜逼一个 互相学习
