### ISSUE TITLE
一年没更新了，没大神接手一下嘛。。。

### ISSUE THREAD

**Issue by lala9662** [hongyangAndroid/okhttputils#417]
不指望原作者了吧，估计很忙，但是这个东西放在这里不动也是浪费啊。。。

半年前用的时候就和最新版的okhttp有兼容的问题和bug，现在okhttp都3.8了。。。

**Comment by mhlistener** [comment]
同问

**Comment by 897902334** [comment]
用OKGo吧，这个时刻在维护,而且挺好用 我觉得。

**Comment by lala9662** [comment]
@mhlistener 放弃这个吧，不想用retrofit的话就用OkGo，一样的结构，比okhttputil好用

**Comment by lala9662** [comment]
@897902334 谢谢，我那天发完贴也看到OKgo了，果断用了。。。

**Comment by i-show** [comment]
我自己参照这个库以及NoHttp 自己写了一个供自己用， 用其他的 可以试一下Nohttp
